FROM ubuntu:20.04
RUN apt-get update && apt-get upgrade -y
# RUN apt-get install -y \
#     git \
#     curl \
#     wget \
#     tzdata 
#     6-69
RUN apt-get install -y apt-utils locales
RUN locale-gen ko_KR.UTF-8
ENV LC_ALL ko_KR.UTF-8